export enum EnvVar {
  PORT = 'PORT',
  DB_CONNECTION = 'DB_CONNECTION',
  RABBITMQ_CONNECTION = 'RABBITMQ_CONNECTION',
  RABBITMQ_EXCHANGE = 'RABBITMQ_EXCHANGE',
  OUTBOX_POLL_INTERVAL_MS = 'OUTBOX_POLL_INTERVAL_MS',
  OUTBOX_BATCH_SIZE = 'OUTBOX_BATCH_SIZE',
}
